FY.Retaguarda/FY.Retaguarda.MVC.V1/Controllers/ClienteController.cs
using FY.Retaguarda.Application.Interfaces;
using FY.Retaguarda.Domain.Entities;
using FY.Retaguarda.MVC.V1.ViewModel;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace FY.Retaguarda.MVC.V1.Controllers
{
    //Annotation Authorize
    public class ClienteController : Controller
    {
        private readonly IClienteAppService _clienteApp;
        public ClienteController(IClienteAppService clienteApp)
        {
            _clienteApp = clienteApp;
        }

        public ActionResult Index()
        {
            try
            {
                var clientes = _clienteApp.GetAll();
                return View(clientes);
            }
            catch (Exception e)
            {
                return View(new List<Cliente>());
            }
        }

        public ActionResult Novo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Novo(ClienteViewModel cliente)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(cliente);

                Cliente c = new Cliente(){
                    Nome = cliente.Nome,
                    CPF = cliente.CPF,
                    Genero = cliente.Genero,
                    DataNascimento = cliente.DataNascimento,
                    Celular = cliente.Celular,
                    Email = cliente.Email,
                    EmpresaId = 1
                };
                _clienteApp.Add(c);

                return RedirectToAction("Index");
            }
            catch (Exception e) {
                //Armazenar exception em log
                return View(cliente);
            }
        }

        public ActionResult Editar(int id)
        {
            try {
                ClienteViewModel cliente;
                var c = _clienteApp.GetById(id);
                if(c.ClienteId > 0)
                {
                    cliente = new ClienteViewModel()
                    {
                        ClienteId = c.ClienteId,
                        Nome = c.Nome,
                        CPF = c.CPF,
                        Genero = c.Genero,
                        DataNascimento = c.DataNascimento,
                        Celular = c.Celular,
                        Email = c.Email,
                        DataCadastro = c.DataCadastro,
                        TotalPontos = c.TotalPontos,
                        EmpresaId = c.EmpresaId
                    };
                    return View(cliente);
                }
                return RedirectToAction("Index");
            }
            catch(Exception e) {
                //Armazenar log de erro
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public ActionResult Editar(ClienteViewModel cliente)
        {
            try
            {
                var c = _clienteApp.GetById(cliente.ClienteId);
                if (c.ClienteId > 0)
                {
                    c.Nome = cliente.Nome;
                    c.CPF = cliente.CPF;
                    c.Genero = cliente.Genero;
                    c.DataNascimento = cliente.DataNascimento;
                    c.Celular = cliente.Celular;
                    c.Email = cliente.Email;
                    c.TotalPontos = cliente.TotalPontos;

                    _clienteApp.Update(c);
                }
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                //Armazenar log de erro
                return RedirectToAction("Index");
            }
        }


        //public ActionResult Manutencao(int? id)
        //{
        //    try
        //    {
        //        ViewBag.TitleManutencao = id != null ? "Editando cliente" : "Novo cliente";
        //        Cliente c = new Cliente();
        //        if (id != null)
        //        {
        //            c = _clienteApp.GetById((int)id);
        //        }
        //        return View(c);
        //    }catch(Exception e)
        //    {
        //        return View(new Cliente());
        //    }
        //}

        //[HttpPost]
        //public ActionResult Manutencao(Cliente c)
        //{
        //    try
        //    {
        //        Cliente cliente = new Cliente();
        //        cliente.PreencherDados(c);
        //        cliente.EmpresaId = 1;
        //        if (cliente.ClienteId > 0){
        //            cliente = _clienteApp.Update(cliente);
        //        }
        //        else{
        //            cliente = _clienteApp.Add(cliente);
        //        }
        //        cliente = _clienteApp.Add(cliente);
        //        return View(cliente);
        //    }
        //    catch(Exception e)
        //    {
        //        return View(c);
        //    }
        //}



    }
}

FY.Retaguarda/FY.Retaguarda.MVC.V1/Controllers/EmpresaController.cs
using System.Web.Mvc;

namespace FY.Retaguarda.MVC.V1.Controllers
{
    //Annotation Authorize
    public class EmpresaController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Manutencao(int? id)
        {
            ViewBag.TitleManutencao = id != null ? "Editando empresa" : "Nova empresa";
            return View();
        }

        public ActionResult MinhasConfiguracoes()
        {
            //Validar identity para pegar código da empresa
            return Redirect("Manutencao/0");
        }
    }
}

FY.Retaguarda/FY.Retaguarda.MVC.V1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FY.Retaguarda.MVC.V1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

FY.Retaguarda/FY.Retaguarda.MVC.V1/Views/Cliente/Editar.cshtml
@model FY.Retaguarda.MVC.V1.ViewModel.ClienteViewModel
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

<div class="block-header">
    <h2>Editar cliente</h2>
</div>
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="body">

                @using (Html.BeginForm("Editar", "Cliente", FormMethod.Post, new { @class = "demo-masked-input" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <!-- Nome -->
                    @Html.LabelFor(model => model.Nome)
                    <div class="form-group">
                        <div class="form-line">
                            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", @placeholder = "Digite o nome do cliente" } })
                            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <!-- Data de Nascimento -->
                    @Html.LabelFor(model => model.DataNascimento)
                    <div class="form-group">
                        <div class="">
                            @Html.EditorFor(model => model.DataNascimento, new
                       {
                           htmlAttributes = new
                           {
                               @class = "form-control data",
                               @placeholder = "Ex: 25/02/2017"
                           }
                       })
                            @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <!-- Gênero -->
                    @Html.LabelFor(model => model.Genero)
                    <div class="form-group">
                        <div class="form-line">
                            <input name="Genero" value="Masculino" type="radio" id="Genero_M" @Html.Raw(Model.Genero == FY.Retaguarda.Domain.ObjectsValue.EnumGenero.Masculino ? "checked" : "") class="with-gap radio-col-amber">
                            <label for="Genero_M">Masculino</label>

                            <input name="Genero" value="Feminino" type="radio" id="Genero_F" @Html.Raw(Model.Genero == FY.Retaguarda.Domain.ObjectsValue.EnumGenero.Feminino ? "checked" : "") class="with-gap radio-col-amber">
                            <label for="Genero_F">Feminino</label>

                            <input name="Genero" value="SemGenero" type="radio" id="Genero_S" @Html.Raw(Model.Genero == FY.Retaguarda.Domain.ObjectsValue.EnumGenero.SemGenero ? "checked" : "") class="with-gap radio-col-amber">
                            <label for="Genero_S">Outros</label>
                        </div>
                    </div>

                    <!-- CPF -->
                    @Html.LabelFor(model => model.CPF)
                    <div class="form-group">
                        <div class="form-line">
                            @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control cpf", @placeholder = "Ex: 000.000.000-00" } })
                            @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
                        </div>
                    </div>

                      <!-- Email  -->
                    @Html.LabelFor(model => model.Email)
                    <div class="form-group">
                        <div class="form-line">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control email", @placeholder = "Ex: exemplo@exemplo.com" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                     <!-- Celular -->
                    @Html.LabelFor(model => model.Celular)
                    <div class="form-group">
                        <div class="form-line">
                            @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control cel", @placeholder = "Ex: (99) 99999-9999" } })
                            @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    
                    <input type="submit" value="Salvar" class="btn btn-primary m-t-15 waves-effect" />
                }

            </div>
        </div>
    </div>
</div>


@*@using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>ClienteViewModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DataCadastro, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DataCadastro, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DataCadastro, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TotalPontos, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TotalPontos, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TotalPontos, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.EmpresaId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EmpresaId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EmpresaId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

FY.Retaguarda/FY.Retaguarda.MVC.V1/Views/Cliente/Index.cshtml
@model IEnumerable<FY.Retaguarda.Domain.Entities.Cliente>
<div class="block-header">
    <h2>Clientes</h2>
</div>
<div class="row clearfix" style="height:200px;">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    Manutenção de clientes
                </h2>
                <!-- [Menu] -->
                <ul class="header-dropdown m-r--5">
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">more_vert</i>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li><a href="javascript:void(0);">Action</a></li>
                            <li><a href="javascript:void(0);">Another action</a></li>
                            <li><a href="javascript:void(0);">Something else here</a></li>
                        </ul>
                    </li>
                </ul>
                <!-- [/Menu]-->

            </div>
            <div class="body">
                <a href="/Cliente/Novo" class="btn bg-purple waves-effect">Novo Cliente</a>
                <br />
                <br />
                <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                    <thead>
                        <tr>
                            <th style="width: 30%;">Nome</th>
                            <th>CPF</th>
                            <th>Celular</th>
                            <th>E-mail</th>
                            <th style="width: auto">Dt. Nascimento</th>
                            <th style="width: 10%"></th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Nome</th>
                            <th>CPF</th>
                            <th>Celular</th>
                            <th>E-mail</th>
                            <th>Dt. Nascimento</th>
                            <th></th>
                        </tr>
                    </tfoot>

                    <!-- [Content] -->
                    <tbody>
                        @foreach(var m in Model){
                            <tr>
                                <td>@m.Nome</td>
                                <td>@m.CPF</td>
                                <td>@m.Celular</td>
                                <td>@m.Email</td>
                                <td>@m.DataNascimento.ToString("dd/MM/yyyy")</td>
                                <td>
                                    <a href="/Cliente/Editar/@m.ClienteId"><i class="material-icons">edit</i></a>
                                    <a href="#"><i class="material-icons">delete</i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                    <!-- [/Content] -->

                </table>
            </div>
        </div>
    </div>
</div>

FY.Retaguarda/FY.Retaguarda.MVC.V1/Views/Cliente/Novo.cshtml
@model FY.Retaguarda.MVC.V1.ViewModel.ClienteViewModel
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

<div class="block-header">
    <h2>Novo cliente</h2>
</div>
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="body">

                @using (Html.BeginForm("Novo", "Cliente", FormMethod.Post, new { @class = "demo-masked-input" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <!-- Nome -->
                    @Html.LabelFor(model => model.Nome)
                    <div class="form-group">
                        <div class="form-line">
                            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", @placeholder = "Digite o nome do cliente" } })
                            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <!-- Data de Nascimento -->
                    @Html.LabelFor(model => model.DataNascimento)
                    <div class="form-group">
                        <div class="">
                            @Html.EditorFor(model => model.DataNascimento, new
                       {
                           htmlAttributes = new
                           {
                               @class = "form-control data",
                               @placeholder = "Ex: 25/02/2017"
                           }
                       })
                            @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <!-- Gênero -->
                    @Html.LabelFor(model => model.Genero)
                    <div class="form-group">
                        <div class="form-line">
                            <input name="Genero" value="Masculino" type="radio" id="Genero_M" class="with-gap radio-col-amber">
                            <label for="Genero_M">Masculino</label>

                            <input name="Genero" value="Feminino" type="radio" id="Genero_F" class="with-gap radio-col-amber">
                            <label for="Genero_F">Feminino</label>

                            <input name="Genero" value="SemGenero" type="radio" id="Genero_S" class="with-gap radio-col-amber">
                            <label for="Genero_S">Outros</label>
                        </div>
                    </div>

                    <!-- CPF -->
                    @Html.LabelFor(model => model.CPF)
                    <div class="form-group">
                        <div class="form-line">
                            @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control cpf", @placeholder = "Ex: 000.000.000-00" } })
                            @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
                        </div>
                    </div>

                      <!-- Email  -->
                    @Html.LabelFor(model => model.Email)
                    <div class="form-group">
                        <div class="form-line">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control email", @placeholder = "Ex: exemplo@exemplo.com" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                     <!-- Celular -->
                    @Html.LabelFor(model => model.Celular)
                    <div class="form-group">
                        <div class="form-line">
                            @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control cel", @placeholder = "Ex: (99) 99999-9999" } })
                            @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    
                    <input type="submit" value="Salvar" class="btn btn-primary m-t-15 waves-effect" />
                }

            </div>
        </div>
    </div>
</div>


@*@using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>ClienteViewModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DataCadastro, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DataCadastro, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DataCadastro, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TotalPontos, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TotalPontos, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TotalPontos, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.EmpresaId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EmpresaId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EmpresaId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

FY.Retaguarda/FY.Retaguarda.MVC.V1/Views/Empresa/Index.cshtml
<div class="block-header">
    <h2>
        Empresas
    </h2>
</div>
<!-- Basic Examples -->
<div class="row clearfix" style="height:200px;">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    Manutenção de empresas
                </h2>

                <!-- Menu -->
                <ul class="header-dropdown m-r--5">
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">more_vert</i>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li><a href="javascript:void(0);">Action</a></li>
                            <li><a href="javascript:void(0);">Another action</a></li>
                            <li><a href="javascript:void(0);">Something else here</a></li>
                        </ul>
                    </li>
                </ul>

            </div>
            <div class="body">
                <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                    <thead>
                        <tr>
                            <th style="width: 50%">Nome</th>
                            <th>CNPJ</th>
                            <th>Status</th>
                            <th style="width: 10%"></th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Nome</th>
                            <th>CNPJ</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                    </tfoot>

                    <!-- Content -->
                    <tbody>
                        <tr>
                            <td>Fidelize You</td>
                            <td>91.926.719/0001-03</td>
                            <td>Ativa</td>
                            <td>
                                <a href="Empresa/Manutencao/0"><i class="material-icons">edit</i></a>
                                <a href="#"><i class="material-icons">delete</i></a>
                            </td>
                        </tr>
                        <tr>
                            <td>Liberty Seguros</td>
                            <td>00.000.000/0000-00</td>
                            <td>Ativa</td>
                            <td>
                                <a href="Empresa/Manutencao/0"><i class="material-icons">edit</i></a>
                                <a href="#"><i class="material-icons">delete</i></a>
                            </td>
                        </tr>
                    </tbody>
                    <!-- Content -->

                </table>
            </div>
        </div>
    </div>
</div>
<!-- #END# Basic Examples -->

FY.Retaguarda/FY.Retaguarda.MVC.V1/Views/Home/Index.cshtml
<div class="block-header">
    <h2>
        Dashboard
    </h2>
</div>

FY.Retaguarda/FY.Retaguarda.MVC.V1/Views/Shared/_FooterSideBarLeft.cshtml
<div class="legal">
    <div class="copyright">
        &copy; @DateTime.Now.Year <a href="javascript:void(0);"> - Fidelize You</a>.
    </div>
    <div class="version">
        <b>Version: </b> 1.0
    </div>
</div>

FY.Retaguarda/FY.Retaguarda.MVC.V1/Views/Shared/_SideBarLeft.cshtml
<div class="menu">
    <ul class="list">
        <li class="header">MENU</li>
        
        <!-- Dashboard -->
        <li>
            <a href="/">
                <i class="material-icons">pie_chart</i>
                <span>Dashboard</span>
            </a>
        </li>

        <!-- Lista de Empresas -->
        <li>
            <a href="/Empresa">
                <i class="material-icons"></i>
                <span>Empresas</span>
            </a>
        </li>

        <!-- Minhas Configurações -->
        <li>
            <a href="/Empresa/MinhasConfiguracoes">
                <i class="material-icons"></i>
                <span>Minhas Configurações</span>
            </a>
        </li>

        <!-- Clientes -->
        <li>
            <a href="/Cliente">
                <i class="material-icons"></i>
                <span>Clientes</span>
            </a>
        </li>
    </ul>
</div>